### PR TITLE
Fixes #67: Save answer POST request

### LINKED ISSUE #67: Save answer POST request
This depends on #72 so work on that first if you're interested and it isn't already assigned.

Add a new `POST` endpoint for the route: `/user/answers/question/{questionNumber}`

In the body of the request, include the necessary attributes (see #72) to save.

(Until auth is implemented, you can use `guest` as the user_id. Just make sure the record exists so the foreign key constraint isn't violated.)

In the main.js browser JavaScript, please submit an AJAX request (using `fetch`) to the above endpoint for any correct answer from the user. We can ignore incorrect answers for now.

This data will be retrieved in #96 if you're interested in working on that part.

### PR DESCRIPTION
**Pull request by josselineperdomo**
Fixes #67 Add a new POST endpoint to create a new user answer.

### CODE REVIEW

**Review by apoorva-mk — COMMENTED** [review]
Hi, please resolve the conflicts

File: public/scripts/main.js [hunk 1]
```diff
@@ -422,3 +423,24 @@ window.addEventListener('focus', function (e) {
...
 });
+
+function createUserAnswer(questionNo, isCorrect, elapsedTimeMs){
+  let requestBody = {
+    userId: 'guest',
+    isCorrect: isCorrect,
+    elapsedTimeMs: elapsedTimeMs
+  }
+
+  fetch('http://localhost:3000/user/answers/question/' + questionNo, {
```
Comment (apoorva-mk) [inline public/scripts/main.js:434]: Hey, hardcoding the address will be an issue.

**Review by apoorva-mk — COMMENTED** [review]
Hi, please resolve the conflicts

File: public/scripts/main.js (hunk 1 above)
Comment (josselineperdomo) [reply public/scripts/main.js]: Oh! My mistake :flushed: . Fixed in the next commit

File: JS/orm.js [hunk 2]
```diff
@@ -27,6 +27,7 @@ UserAnswers.init(
   {
     id:{
       primaryKey : true,
+      autoIncrement: true,
       type: Sequelize.INTEGER,
     },
```
Comment (vegetabill) [inline JS/orm.js:32]: Turns out our whole config for `id` is just the default, including what you added, so let's remove this entire block and it will work correctly.

File: routes/routes.js [hunk 3]
```diff
@@ -9,4 +11,22 @@ router.get('/cheatsheet', (req,res) => {
     res.render('cheatsheet');
 })
 
+router.post('/user/answers/question/:questionNumber', (req, res) => {
+    if(req.body.id) {
+		return res.status(400).json({'message': 'ID should not be provided'});
+    }    
+    UserAnswers.create({
+        user_id: req.body.userId,
```
Comment (vegetabill) [inline routes/routes.js:19]: Since neither Auth0 or fake auth is yet implemented, can you add a line above this that calls `User.findOrCreate({ where: { id: req.body.userId } })`...otherwise the insert won't work because the user will never exist.

It should have a comment saying that it's just needed until https://github.com/Techtonica/keyboard-shortcuts-practice/issues/74 is implemented.

Thanks!

File: routes/routes.js [hunk 4]
```diff
@@ -9,4 +11,22 @@ router.get('/cheatsheet', (req,res) => {
...
+        question_number: req.params.questionNumber,
+        is_correct: req.body.isCorrect,
+        elapsed_time_ms: req.body.elapsedTimeMs
+    }).then(userAnswer => {
+        return res.status(201).json(userAnswer)
```
Comment (vegetabill) [inline routes/routes.js:24]: Nice use of 201!

**Review by vegetabill — CHANGES_REQUESTED** [review]
Looks great! Main thing is just to fix that URL in fetch to not be absolute.

File: JS/orm.js (hunk 2 above)
Comment (josselineperdomo) [reply JS/orm.js]: Removed the autoincrement value, should I remove the whole `id` field definition?

File: routes/routes.js (hunk 3 above)
Comment (josselineperdomo) [reply routes/routes.js]: Yes! You're right, I wanted to use the Sequelize errors but this is a more explicit way to validated de fk :blush:  I already fixed in my recent commit.

File: public/scripts/main.js [hunk 5]
```diff
@@ -422,3 +423,24 @@ window.addEventListener('focus', function (e) {
...
 });
+
+function createUserAnswer(questionNo, isCorrect, elapsedTimeMs){
+  let requestBody = {
+    userId: 'guest',
+    isCorrect: isCorrect,
+    elapsedTimeMs: elapsedTimeMs
+  }
+  
+  fetch(document.URL + 'user/answers/question/' + questionNo, {
```
Comment (vegetabill) [inline public/scripts/main.js:434]: This works fine. For future reference, you can also omit the entire hostname, etc and just use a relative URL, e.g. `fetch('/user/...')`

**Review by vegetabill — APPROVED** [review]
Revisions look great! Thanks
